---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 30s
  path: ./infrastructure/gorilla/cne02
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

